---
- name: set up the server
  hosts: all
  sudo: yes
  tasks:
    - name: update package lists
      apt: update-cache=yes
    - name: upgrade all packages
      apt: upgrade=dist
    - name: install basic and necessary packages
      apt: pkg={{ item }} state=latest
      tags: [packages]
      with_items:
        - vim
        - git
        - nginx
        - nodejs
        - npm
        - exim4
    - name: add a 'node' alias for nodejs
      file: path=/usr/local/bin/node state=link src=/usr/bin/nodejs
    - name: install grunt
      npm: name=grunt-cli state=present global=yes

- name: set up a mail server
  hosts: all
  sudo: yes
  tasks:
    - name: install our copy of update_exim4.conf.conf
      copy: src=update-exim4.conf.conf dest=/etc/exim4/update-exim4.conf.conf
    - name: generate exim4 configuration
      command: update-exim4.conf
    - name: reload exim4
      service: name=exim4 state=reloaded

- name: set up the architecture for the ppdc website
  hosts: all
  sudo: yes
  tasks:
    - name: create the user group
      group: name=ppdc-website state=present system=yes
    - name: add www-data to the user group
      user: name=www-data append=yes groups=ppdc-website
    - name: create the user and its home directory
      user: name=ppdc-website state=present system=yes group=ppdc-website
    - name: allow us to connect directly as the website user
      shell: "mkdir -p -m 700 ~ppdc-website/.ssh && cp ~{{ansible_ssh_user}}/.ssh/authorized_keys ~ppdc-website/.ssh && chown -R ppdc-website: ~ppdc-website/.ssh/ creates=/home/ppdc-website/.ssh/authorized_keys"
    - name: create the directory under /srv
      file: path=/srv/ppdc-website state=directory owner=ppdc-website group=ppdc-website mode=750
